### ISSUE TITLE
About the pt dataset

### ISSUE THREAD

**Issue by nicosouth** [DUOMO/TransGPT#1]
hello! I download the pt dataset.

I read the contents of the transgpt-pt.txt. I found three problems:
i) A large number of sentences are forcibly broken into multiple sentences, and it seems that the length is not fixed.
ii) Some special symbols (such as mathematical formulas) appear in the text with a confusing format and without special treatment.
iii) Some meaningless pure numbers appear as separate text.

I'd like to consult you that whether these low-quality data affect training model. 
Thank you!

**Comment by DUOMO** [comment]
Hello! These low-quality data indeed may potentially affect the training model. The broken sentences and confusing format of special symbols may cause the model to learn incorrect patterns and generate inaccurate sentences. 

We are working on another cleaning and preprocessing process before training the model to ensure better quality results. Thank you for your valuable suggestions✨ We welcome your contributions to the clean data construction project.

**Comment by nicosouth** [comment]
您好，我是宋迎杰，您的信件我已收到，如有需要，我将尽快予以回复，谢谢。

**Comment by nicosouth** [comment]
Thank you! 
Previously, I thought these low-quality data were added deliberately to enhance the robustness of the model.
