### ISSUE TITLE
基于TransGPT专利对TransGPT的发展和后续使用上的影响？

### ISSUE THREAD

**Issue by DaheChina** [DUOMO/TransGPT#21]
TransGPT做的已经基本成型了，也已经开源并且可以免费商用，但是下面这个发明专利的注册，基本把TransGPT的内容都涵盖了，不知道这个是不是会对后面使用TransGPT的人或者组织产生比较大的影响？公司能拿来申请专利吗？申请专利后，别人也采用TransGPT来开发产品了，岂不是侵犯了这家公司的发明专利？！ ( ⊙ o ⊙ )
基于TransGPT的综合交通运行服务系统和方法
https://zhuanli.tianyancha.com/e9266800e06665e52ae6adfc7f969cc9
[基于TransGPT的综合交通运行服务系统和方法.pdf](https://github.com/DUOMO/TransGPT/files/13722722/TransGPT.pdf)

**Comment by DaheChina** [comment]
按照下面这段话的解释，遵循Apache-2.0而衍生的专利，如果对其它衍生软件主张侵权，则开源贡献者对该主张侵权组织的的许可终止。不知道这样解释是否正确，是否还有其它风险、问题？

下面这段对于Apache-2.0的专利等权利进行了解释，仅供参考：

在开源许可协议中明确了贡献者授予专利许可的协议例如包括 Apache License， 2.0(Apache-2.0)、GNU General Public License version 3 (GPL-3.0)、Mozilla Public License 2.0 (MPL-2.0)等，其中对贡献者和获取者二者都有专利权行驶的约束。

作为示例，在开源许可协议Apache-2.0中针对专利许可明确规定了：受限于本许可证的条款，每个贡献者特此授予获取者永久的、全球性的、非排他的、免费的、免许可费的、不可撤销的专利许可证，以制造、已经制造、使用、许诺销售、销售、进口或以其他方式转让作品（即，开源软件），其中该许可仅适用于贡献者单独贡献、或者基于该贡献的作品必定侵犯的专利权利要求；如果获取者对任何实体提出专利诉讼，声称该作品或作品内所合并的各贡献构成直接或共同专利侵权，则根据本许可证授予你该作品的任何专利许可应自提起该诉讼之日起终止。 

可以看出，在Apache-2.0许可协议下，对贡献者而言，需要向获取者免费许可所贡献的软件中的专利使用；对于获取者而言，如果获取者针对贡献者所贡献的软件或相应的衍生软件主张侵权，则贡献者的许可终止，这使得能够降低与开源软件相关的专利诉讼风险，推动开源软件的发展。因此，在Apache-2.0许可协议下，约束了专利权的行驶，从而促进了开源软件的传播和技术共享。此外，在GPL-3.0开源协议中的规定了GPL保证专利不能用于使开源程序用于向获取者收取使用费。 作者：Posyol https://www.bilibili.com/read/cv25748549/ 出处：bilibili

**Comment by WinnieHAN** [comment]
使用TransGPT · 致远的公司申请专利的问题，请咨询专业律所。
