### ISSUE TITLE
模型推理不准

### ISSUE THREAD

**Issue by weaver-teng** [DUOMO/TransGPT#22]
您的模型用起来了，但是不太准，想问一下我现在用的TransGPT-MM-v1模型，已经被多少的数据训练过了？我如果想让该模型推理的更准一些，大约还要再用多少的数据去训练？

**Comment by zhumorui** [comment]
我也试了，非常不准确。不知道单模态的准确度会不会高一些。

**Comment by WinnieHAN** [comment]
推荐尝试换用更好的基础模型。
