### ISSUE TITLE
实时信息

### ISSUE THREAD

**Issue by CaralHsi** [DUOMO/TransGPT#3]
你好，我注意到TransGPT包含了部分天气信息的问答，这部分极其依赖实时数据，模型有做对实时数据的处理吗？

Hello,
    It is amazing that the TransGPT could output such a perfect solution. I noticed that there is a QA show case about the weather question. Weather is a kind of topic which highly depend on the online data. May I know that whether you consider the online data into the LLM and how you tackle with such problem?

**Comment by ErvinZzz** [comment]
> 你好，我注意到TransGPT包含了部分天气信息的问答，这部分极其依赖实时数据，模型有做对实时数据的处理吗？
> 
> Hello, It is amazing that the TransGPT could output such a perfect solution. I noticed that there is a QA show case about the weather question. Weather is a kind of topic which highly depend on the online data. May I know that whether you consider the online data into the LLM and how you tackle with such problem?


我对算法进行了一下测试， 结论是无法预测实时数据；（感觉对实时数据的处理依赖于plugin_store文件夹中的内容，但是没有展示该如何和llm模型一起使用）

**Comment by DUOMO** [comment]
plugin之前没有封装在langchain里面，我们最近打算把这个封装进langchain，方便和其他app一起调用。

**Comment by liangzz1991** [comment]
@DUOMO 看示例支持图片输入，模型貌似不支持多模态，这是怎么处理的

**Comment by TerrenceVarada** [comment]
看到可以预测交通情况，请教一下这里要接入什么数据？

**Comment by threeColorFr** [comment]
> @DUOMO 看示例支持图片输入，模型貌似不支持多模态，这是怎么处理的

Multi-modal versions will be released after a period of time

**Comment by DUOMO** [comment]
Already released.
